<a href="https://colab.research.google.com/github/malcolmlett/ml-learning/blob/feature%2F20250110-explain-near-zero-grads/Learning_visualisations_v12a_MatMulExplainer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Multiplication explainer
A tool for explaining the output value from matrix multiplication, particularly for near-zero outputs.

In [195]:
import os
if os.path.isdir('repo'):
  # discard any local changes and update
  !cd repo && git reset --hard HEAD
  !cd repo && git fetch
else:
  !git clone https://github.com/malcolmlett/ml-learning.git repo

# TEMP use branch
!cd repo && git checkout feature/20250110-explain-near-zero-grads

# lock to revision
#!cd repo && git checkout ea80c40
!cd repo && git pull

import sys
sys.path.append('repo')

import matmul_explainer as me
from importlib import reload
reload(me)

HEAD is now at 3f3a8a3 Bug fix
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 425 bytes | 425.00 KiB/s, done.
From https://github.com/malcolmlett/ml-learning
   3f3a8a3..6c5ed2f  feature/20250110-explain-near-zero-grads -> origin/feature/20250110-explain-near-zero-grads
Already on 'feature/20250110-explain-near-zero-grads'
Your branch is behind 'origin/feature/20250110-explain-near-zero-grads' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Updating 3f3a8a3..6c5ed2f
Fast-forward
 matmul_explainer_test.py | 27 +++++++++++++++++++++++++--
 1 file changed, 25 insertions(+), 2 deletions(-)


<module 'matmul_explainer' from '/content/repo/matmul_explainer.py'>

In [196]:
import matmul_explainer_test
reload(matmul_explainer_test)
matmul_explainer_test.run_test_suite()

In [97]:
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp
import math

## Classification
First we need to be able to classify the components that make up the matrix multiplication results.

We do that with a number of functions:

```
def classify_terms():
  return ['PP', 'PZ', 'PN', 'ZP', 'ZZ', 'ZN', 'NP', 'NZ', 'NN']

def matmul_classify(x1, x2, confidence: float=0.95, threshold1: float = None, threshold2: float = None):
 ...
 return counts, sums
```


In [63]:
# Standard ordered terms
print(f"Terms: {me.classify_terms()}")

Terms: ['PP', 'PZ', 'PN', 'ZP', 'ZZ', 'ZN', 'NP', 'NZ', 'NN']


In [167]:
# Simple 2D matmul explanation
reload(me)
a = np.arange(0.0, 1.0, 0.1)
a = np.tile(a, (10,1))
print(f"a = b = {a}")

counts, sums = me.matmul_classify(a, a, confidence=0.75)

print()
print("Details...")
for i, name in enumerate(me.classify_terms()):
  if np.sum(counts[:,:,i]) > 0:
    print(f"Counts({name}): {counts[:,:,i]}")
for i, name in enumerate(me.classify_terms()):
  if np.sum(counts[:,:,i]) > 0:
    print(f"Sums({name}): {sums[:,:,i]}")

print()
print("Summary...")
print(f"Classes: {me.classify_terms()}")
print(f"Counts by class: {np.sum(counts, axis=(0,1))}")
print(f"Sums by class: {np.sum(sums, axis=(0,1))}")

print()
print("Validation...")
print(f"True matmul: {np.matmul(a, a)}")
print(f"Derived matmul: {np.sum(sums, axis=-1)}")


a = b = [[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]]

Details...
Counts(PP): [[0 0 8 8 8 8 8 8 8 8]
 [0 0 8 8 8 8 8 8 8 8]
 [0 0 8 8 8 8 8 8 8 8]
 [0 0 8 8 8 8 8 8 8 8]
 [0 0 8 8 8 8 8 8 8 8]
 [0 0 8 8 8 8 8 8 8 8]
 [0 0 8 8 8 8 8 8 8 8]
 [0 0 8 8 8 8 8 8 8 8]
 [0 0 8 8 8 8 8 8 8 8]
 [0 0 8 8 8 8 8 8 8 8]]
Counts(PZ): [[8 8 0 0 0 0 0 0 0 0]
 [8 8 0 0 0 0 0 0 0 0]
 [8 8 0 0 0 0 0 0 0 0]
 [8 8 0 0 0 0 0 0 0 0]
 [8 8 0 0 0 0 0 0 0 0]
 [8 8 0 0 0 0 0 0 0 0]
 [8 8 0 0 0 0 0 0 0 0]
 [8 8 0 0 0 0 0 0 0 0]
 [8 8 0 0 0 0 0 0 0 0]
 [8 8 0 0 0 0 0 0 0 0]]
Counts(ZP): [[0 0 2 2 2 2 2 2 2 2]
 [0 0 2 2 2 2 2 2 2 2]
 [0 0

In [176]:
# 2D convolution explanation
a = np.arange(0.0, 0.9, 0.1)
a = np.tile(a, (9,1)).astype(np.float32)
a = tf.reshape(a, shape=(1,9,9,1))
print(f"a = b: {a.shape} = {a[0,:,:,0]}")

k = np.array([
    [-1, 0, -1],
    [+1, +1, +1],
    [-1, 0, -1]
]).astype(np.float32)
k = tf.reshape(k, shape=(3,3,1,1))
print(f"k = {k.shape} = {k[:,:,0,0]}")

counts, sums = me.conv_classify(a, k, confidence=0.75)
print()
print("Results...")
print(f"Shapes: counts={counts.shape}, sums={sums.shape}")
for i, name in enumerate(me.classify_terms()):
  if np.sum(counts[...,i]) > 0:
    print(f"Counts({name}): {counts[0,:,:,0,i]}")
for i, name in enumerate(me.classify_terms()):
  if np.sum(counts[...,i]) > 0:
    print(f"Sums({name}): {sums[0,:,:,0,i]}")

print()
print("Summary...")
print(f"Classes: {me.classify_terms()}")
print(f"Counts by class: {np.sum(counts, axis=(0,1,2,3))}")
print(f"Sums by class: {np.sum(sums, axis=(0,1,2,3))}")

print()
print("Validation...")
expected_conv = tf.nn.convolution(a, k)
derived_conv = tf.reduce_sum(sums, axis=-1)
print(f"True conv: {expected_conv.shape} = {expected_conv[0,:,:,0]}")
print(f"Derived conv: {derived_conv.shape} = {derived_conv[0,:,:,0]}")
print(f"Devired conv == true conv: {np.allclose(expected_conv, derived_conv)}")


a = b: (1, 9, 9, 1) = [[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]]
k = (3, 3, 1, 1) = [[-1.  0. -1.]
 [ 1.  1.  1.]
 [-1.  0. -1.]]

Results...
Shapes: counts=(1, 7, 7, 1, 9), sums=(1, 7, 7, 1, 9)
Counts(PP): [[1. 2. 3. 3. 3. 3. 3.]
 [1. 2. 3. 3. 3. 3. 3.]
 [1. 2. 3. 3. 3. 3. 3.]
 [1. 2. 3. 3. 3. 3. 3.]
 [1. 2. 3. 3. 3. 3. 3.]
 [1. 2. 3. 3. 3. 3. 3.]
 [1. 2. 3. 3. 3. 3. 3.]]
Counts(PZ): [[0. 2. 2. 2. 2. 2. 2.]
 [0. 2. 2. 2. 2. 2. 2.]
 [0. 2. 2. 2. 2. 2. 2.]
 [0. 2. 2. 2. 2. 2. 2.]
 [0. 2. 2. 2. 2. 2. 2.]
 [0. 2. 2. 2. 2. 2. 2.]
 [0. 2. 2. 2. 2. 2. 2.]]
Counts(PN): [[2. 2. 4. 4. 4. 4. 4.]
 [2. 2. 4. 4. 4. 4. 4.]
 [2. 2. 4. 4. 4. 4. 4.]
 [2. 2. 4. 4. 4. 4. 4.]
 [2. 2. 4. 4. 4. 4. 4.]
 [

In [197]:
# 1D convolution explanation
a = np.arange(0.0, 0.9, 0.1).astype(np.float32)
a = tf.reshape(a, shape=(1,9,1))
print(f"a = b: {a.shape} = {a[0,:,0]}")

k = np.array([-1, 0, -1]).astype(np.float32)
k = tf.reshape(k, shape=(3,1,1))
print(f"k = {k.shape} = {k[:,0,0]}")

counts, sums = me.conv_classify(a, k, confidence=0.90)
print()
print("Results...")
print(f"Shapes: counts={counts.shape}, sums={sums.shape}")
for i, name in enumerate(me.classify_terms()):
  if np.sum(counts[...,i]) > 0:
    print(f"Counts({name}): {counts[0,:,0,i]}")
for i, name in enumerate(me.classify_terms()):
  if np.sum(counts[...,i]) > 0:
    print(f"Sums({name}): {sums[0,:,0,i]}")

print()
print("Summary...")
print(f"Classes: {me.classify_terms()}")
print(f"Counts by class: {np.sum(counts, axis=(0,1,2))}")
print(f"Sums by class: {np.sum(sums, axis=(0,1,2))}")

print()
print("Validation...")
expected_conv = tf.nn.convolution(a, k)
derived_conv = tf.reduce_sum(sums, axis=-1)
print(f"True conv: {expected_conv.shape} = {expected_conv[0,:,0]}")
print(f"Derived conv: {derived_conv.shape} = {derived_conv[0,:,0]}")
print(f"Devired conv == true conv: {np.allclose(expected_conv, derived_conv)}")

a = b: (1, 9, 1) = [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8]
k = (3, 1, 1) = [-1.  0. -1.]

Results...
Shapes: counts=(1, 7, 1, 9), sums=(1, 7, 1, 9)
Counts(PZ): [1. 1. 1. 1. 1. 1. 1.]
Counts(PN): [1. 2. 2. 2. 2. 2. 2.]
Counts(ZN): [1. 0. 0. 0. 0. 0. 0.]
Sums(PZ): [0. 0. 0. 0. 0. 0. 0.]
Sums(PN): [-0.2       -0.4       -0.6       -0.8       -1.        -1.2
 -1.4000001]
Sums(ZN): [0. 0. 0. 0. 0. 0. 0.]

Summary...
Classes: ['PP', 'PZ', 'PN', 'ZP', 'ZZ', 'ZN', 'NP', 'NZ', 'NN']
Counts by class: [ 0.  7. 13.  0.  0.  1.  0.  0.  0.]
Sums by class: [ 0.   0.  -5.6  0.   0.   0.   0.   0.   0. ]

Validation...
True conv: (1, 7, 1) = [-0.2       -0.4       -0.6       -0.8       -1.        -1.2
 -1.4000001]
Derived conv: (1, 7, 1) = [-0.2       -0.4       -0.6       -0.8       -1.        -1.2
 -1.4000001]
Devired conv == true conv: True
